AWSTemplateFormatVersion: 2010-09-09
Description: Globe EC2 - Linux Application Deployment
Parameters:
  Project:
    Description: Name of the Project
    MinLength: '1'
    Type: String
    Default: 'ECSINAWS:PH01'
  Platform:
    Description: Name of the platform
    MinLength: '1'
    Type: String
    Default: EVOLVED CHARGING SUITE (ECS) - DR
  WBSCode:
    Description: Tag for WBSCode
    Type: String
    MinLength: '1'
    Default: ISG-ECSDREGN-20-SV-DV
  CostCenter:
    Description: Tag for Cost Center
    MinLength: '1'
    Type: String
    Default: ISG12-G1
  Deployment:
    Description: Select the status of the Deployment
    Type: String
    Default: 'PROD:PREP'
  ApplicationVendor:
    Description: Tag for Application Vendor
    MinLength: '1'
    Type: String
    Default: OPENET
  PlatformName:
    Description: PlatformName
    MinLength: '1'
    Type: String
    Default: ECS
  PlatformOwner:
    Description: Name of the Project
    MinLength: '1'
    Type: String
    Default: Matthew Louise Samonte
  Domain:
    Description: Name of the Domain
    MinLength: '1'
    Type: String
    Default: Technology Group
  PIN:
    Description: 'PIN #'
    MinLength: '1'
    Type: String
    Default: PIN-000000002781
  SystemTier:
    Description: Tier
    MinLength: '1'
    Type: String
    Default: '1'
  SG1:
    Description: Security Groups
    MinLength: '1'
    Type: String
    Default: sg-00b06d6cef1fc2e40
  SG2:
    Description: Security Groups
    MinLength: '1'
    Type: String
    Default: sg-058d34bc94680faff
Resources:
  AggCDRInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.2xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-01d0f19d9c4370fd5
      PrivateIpAddress: 10.68.94.8
      Tags:
        - Key: Name
          Value: VMOPMADR03
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmopmadr03 > /etc/hostname
          shutdown -r now
  IGWApp2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.4xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      IamInstanceProfile: LZ-ECSDR-S3Policy
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-06af50a0b15958454
      PrivateIpAddress: 10.68.94.10
      Tags:
        - Key: Name
          Value: VMIGWADR02
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmigwadr02 > /etc/hostname
          shutdown -r now
  IGWApp3:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.4xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      IamInstanceProfile: LZ-ECSDR-S3Policy
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-06af50a0b15958454
      PrivateIpAddress: 10.68.94.11
      Tags:
        - Key: Name
          Value: VMIGWADR03
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmigwadr03 > /etc/hostname
          shutdown -r now
  SNM02:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.13
      Tags:
        - Key: Name
          Value: VMSNMADR02
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr02 > /etc/hostname
          shutdown -r now
  SNM03:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.14
      Tags:
        - Key: Name
          Value: VMSNMADR03
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr03 > /etc/hostname
          shutdown -r now
  SNM04:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.15
      Tags:
        - Key: Name
          Value: VMSNMADR04
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr04 > /etc/hostname
          shutdown -r now
  SNM05:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.16
      Tags:
        - Key: Name
          Value: VMSNMADR05
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr05 > /etc/hostname
          shutdown -r now
  SNM06:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.17
      Tags:
        - Key: Name
          Value: VMSNMADR06
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr06 > /etc/hostname
          shutdown -r now
  SNM07:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.18
      Tags:
        - Key: Name
          Value: VMSNMADR07
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr07 > /etc/hostname
          shutdown -r now
  SNM08:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.12xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-06c92beb29fd981a9
      ImageId: ami-016fbabb5ec235d81
      PrivateIpAddress: 10.68.94.19
      Tags:
        - Key: Name
          Value: VMSNMADR08
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmsnmadr08 > /etc/hostname
          shutdown -r now
  IGWDB2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.4xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-0641d3bc298e5fceb
      ImageId: ami-063a47a2612887bed
      PrivateIpAddress: 10.68.94.189
      Tags:
        - Key: Name
          Value: VMIGWDDR02
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmigwddr02 > /etc/hostname
          shutdown -r now
  IGWDB3:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: m5.4xlarge
      SecurityGroupIds:
        - Ref: SG1
        - Ref: SG2
      SubnetId: subnet-0641d3bc298e5fceb
      ImageId: ami-063a47a2612887bed
      PrivateIpAddress: 10.68.94.190
      Tags:
        - Key: Name
          Value: VMIGWDDR03
        - Key: Project
          Value: !Ref Project
        - Key: WBS Code
          Value: !Ref WBSCode
        - Key: Deployment
          Value: !Ref Deployment
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Application Vendor
          Value: !Ref ApplicationVendor
        - Key: PIN
          Value: !Ref PIN
        - Key: System Tier
          Value: !Ref SystemTier
        - Key: Platform Owner
          Value: !Ref PlatformOwner
        - Key: Domain
          Value: !Ref Domain
        - Key: Platform Name
          Value: !Ref PlatformName
        - Key: System
          Value: !Ref PlatformName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo echo vmigwddr02 > /etc/hostname
          shutdown -r now