---
AWSTemplateFormatVersion: '2010-09-09'
Description: Architecture to host Postgresql RDS.
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  BusinessUnit:
    Description: Name of the Organization
    Type: String

  DBAllocatedStorage:
    Description: The size of the database (Gb)
    Type: Number
    Default: 400

  DBClass:
    Description: Database instance class
    Type: String
    Default: "db.m5.xlarge"

  DbName:
    Description: Database Name for postgresql
    Type: String
    Default: "apimprodDB"

  BackupRetentionPeriod:
    Description: Backup Retention Period in Days.
    Type: String
    Default: 2

  PreferredBackupWindow:
    Description: Preferred Backup Window Time (UTC).
    Type: String
    Default: 23:00-23:30

  DBMultiAZ:
    Description: 'Specifies if the database instance is deployed to multiple Availability Zones for HA.'
    Type: String
    Default: true
    AllowedValues: [true, false]

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/vpc:1}}"
      GroupDescription: Access to the RDS server
      SecurityGroupIngress:
        - CidrIp: !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/vpccidr:1}}"
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
      Tags:
        - Key: Name
          Value: rds-apm-prdisg-sg01
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18
        - Key: Platform Name
          Value: APIMONETIZATION 

  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}-postgresqql
      Description: !Join [" ", [!Ref EnvironmentName, "rds instance secret"]]
      GenerateSecretString:
        SecretStringTemplate: '{"username": "root"}'
        GenerateStringKey: '********'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: AppName
          Value: !Join ["-", [!Ref BusinessUnit, !Ref EnvironmentName, "PostgreSQLSecret"]]
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION 
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18
        - Key: Platform Name
          Value: APIMONETIZATION   

  pgDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private Subnet Group for RDS
      DBSubnetGroupName: !Join ["-", [!Ref BusinessUnit, !Ref EnvironmentName, "subnet"]]
      SubnetIds: 
        - !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/dbsubnet1:1}}"
        - !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/dbsubnet2:1}}"
        - !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/dbsubnet3:1}}"
      Tags:
        - Key: "Name"
          Value: apmdatabaseproduction
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION 
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18
        - Key: Platform Name
          Value: APIMONETIZATION 

  pgDBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Database Parameter Group + pg_stat_statements
      Family: postgres11
      Parameters:
        shared_preload_libraries: pg_stat_statements
      Tags:
        - Key: "Name"
          Value: APMPRD
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18
        - Key: Platform Name
          Value: APIMONETIZATION 

  pgDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DbName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBClass
      DBInstanceIdentifier: vmapmdpd01
      StorageType: gp2
      MultiAZ: !Ref DBMultiAZ
      Engine: postgres
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      PreferredBackupWindow: !Ref PreferredBackupWindow
      StorageEncrypted: true
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSInstanceRotationSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSInstanceRotationSecret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref pgDBSubnetGroup
      DBParameterGroupName: !Ref pgDBParamGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: VMAPMDPD01
        - Key: Businessunit
          Value: !Ref BusinessUnit
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Role
          Value: rds
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION  
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18
        - Key: Platform Name
          Value: APIMONETIZATION 

  pgDBReadReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      SourceDBInstanceIdentifier: !Ref pgDB
      DBInstanceClass: !Ref DBClass
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref BusinessUnit, !Ref EnvironmentName, "rds"]]
        - Key: Businessunit
          Value: !Ref BusinessUnit
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Role
          Value: RDS Read Replica
        - Key: Platform Name
          Value: APIMONETIZATION 
        - Key: Backup 
          Value: Weekly
        - Key: Deployment
          Value: PROD:PREP
        - Key: Project
          Value: APIMONETIZATION  
        - Key: Cost Center
          Value: ISG-TECAPIMON/18
        - Key: WBS Code
          Value: ISG-TECAPIMON/18

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MyRDSInstanceRotationSecret
      TargetId: !Ref pgDB
      TargetType: AWS::RDS::DBInstance

  RDSEventSubscription:
    Type: "AWS::RDS::EventSubscription"
    Properties: 
      Enabled: true
      EventCategories:
        - "configuration change"
        - "failure"
        - "deletion"
        - "backup"
        - "availability"
        - "failover"
        - "low storage"
        - "maintenance"
        - "notification"
        - "recovery"
        - "restoration"
        - "creation"
      SnsTopicArn: !Sub "{{resolve:ssm:/${BusinessUnit}/${EnvironmentName}/sns:1}}"
      SourceIds:
        - !Ref pgDB
      SourceType: "db-instance"

Outputs:
  RDSID:
    Description: InstanceId of the newly created RDS Server
    Value: !Ref pgDB
  RDSReadReplicaID:
    Description: InstanceId of the newly created RDS Server
    Value: !Ref pgDBReadReplica
